version: "3.8"

services:
  doom-emacs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ELIXIR_VERSION: ${ELIXIR_VERSION:-latest}
    volumes:
      - $HOME:/mnt/host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    entrypoint: ["emacs"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
